### ISSUE TITLE
code 70006 Error while toggling video transmission 

### ISSUE THREAD

**Issue by ck505778675** [VoiSmart/pjsip-android#100]
I use opensips as server,  pjsip as client, coturn as turn server ,audio is ok ,but video is not ok ,please help me! 

client log
E/SipCall: Error while toggling video transmission
    java.lang.Exception: Title:       pjsua_call_set_vid_strm(id, op, &prm)
    Code:        70006
    Description: Not found (PJ_ENOTFOUND)
    Location:    ../src/pjsua2/call.cpp:633
    
        at org.pjsip.pjsua2.pjsua2JNI.Call_vidSetStream(Native Method)
        at org.pjsip.pjsua2.Call.vidSetStream(Call.java:171)
        at net.gotev.sipservice.SipCall.setVideoMute(SipCall.java:543)
        at net.gotev.sipservice.SipCall.onCallState(SipCall.java:133)
        at org.pjsip.pjsua2.pjsua2JNI.SwigDirector_Call_onCallState(pjsua2JNI.java:2426)
server log :

Apr 29 18:54:55 [13075] DBG:core:build_res_buf_from_sip_res:  old size: 1299, new size: 1209
Apr 29 18:54:55 [13075] DBG:core:build_res_buf_from_sip_res: copied size: orig:106, new: 1209, rest: 1193 msg=
SIP/2.0 200 OK
Via: SIP/2.0/UDP 115.44.241.207:47068;rport=47068;received=115.44.241.207;branch=z9hG4bKPj0f4df2e8-1a8c-4ccc-b2e1-5ef3dc575c69
Call-ID: 1879a7f0-c7c2-4440-9905-1ff4336fce05
From: <sip:hoho@sip.1.codecc.cn>;tag=8e2eee3e-960c-47f8-b510-bb4ef7a31209
To: <sip:wangcker@sip.1.codecc.cn>;tag=e52a8520-ad4f-46e7-8f3f-af742f13800b
CSeq: 10944 UPDATE
Session-Expires: 1800;refresher=uac
Require: timer
Contact: <sip:wangcker@115.44.241.207:49025;ob>;+sip.ice
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Supported: replaces, 100rel, timer, norefersub
Content-Type: application/sdp
Content-Length:   533

v=0
o=- 3797146494 3797146497 IN IP4 192.168.1.105
s=pjmedia
b=AS:117
t=0 0
a=X-nat:0
m=audio 50154 RTP/AVP 120 96
c=IN IP4 192.168.1.105
b=TIAS:96000
a=sendrecv
a=rtpmap:120 opus/48000/2
a=fmtp:120 useinbandfec=1
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-16
a=ice-ufrag:543dc818
a=ice-pwd:3cc8f482
a=rtcp:52485 IN IP4 192.168.1.105
a=candidate:Hc0a80169 1 UDP 2130706431 192.168.1.105 50154 typ host
a=candidate:Hc0a80169 2 UDP 2130706430 192.168.1.105 52485 typ host
m=video 0 RTP/AVP 31
c=IN IP4 127.0.0.1

Apr 29 18:54:55 [13075] DBG:core:_shm_resize: resize(0) called
Apr 29 18:54:55 [13075] DBG:tm:insert_timer_unsafe: [2]: 0x7fbb0ce383d8 (2998)
Apr 29 18:54:55 [13075] DBG:tm:relay_reply: sent buf=0x7fbb0ebc70e0: SIP/2.0 2..., shmem=0x7fbb0ce367f8: SIP/2.0 2
Apr 29 18:54:55 [13075] DBG:tm:cleanup_uac_timers: RETR/FR timers reset
Apr 29 18:54:55 [13075] DBG:tm:t_unref: UNREF_UNSAFE: [0x7fbb0ce38358] after is 0
Apr 29 18:54:55 [13075] DBG:core:destroy_avp_list: destroying list (nil)
Apr 29 18:54:55 [13075] DBG:core:receive_msg: cleaning up
Apr 29 18:54:56 [13076] DBG:tm:utimer_routine: timer routine:4,tl=0x7fbb0ce38578 next=(nil), timeout=2993700000
Apr 29 18:54:56 [13074] DBG:core:udp_read_req: probing packet received len = 2
Apr 29 18:54:57 [13072] DBG:tm:timer_routine: timer routine:2,tl=0x7fbb0ce2efc8 next=0x7fbb0ce339d0, timeout=2994
Apr 29 18:54:57 [13072] DBG:tm:wait_handler: removing 0x7fbb0ce2ef48 from table 
Apr 29 18:54:57 [13072] DBG:tm:delete_cell: delete transaction 0x7fbb0ce2ef48
Apr 29 18:54:57 [13072] DBG:tm:wait_handler: done

**Comment by aenonGit** [comment]
Don't see the video (m video line) in that `sdp`. Maybe that's the problem? are you making a video call?

**Comment by ck505778675** [comment]
yes,make a video call ,but mediaInfo status is PJSUA_CALL_MEDIA_NONE
there is my call code  but  nothing 
SipServiceCommand.makeCall(MainActivity.this, "sip:"+sipAccountData.getUsername()+"@"+sipAccountData.getRealm(), sipUri.toString(),true,false);

**Comment by ck505778675** [comment]
the error occur at here

           } else if (callState == pjsip_inv_state.PJSIP_INV_STATE_CONFIRMED) {
                checkAndStopLocalRingBackTone();
                connectTimestamp = System.currentTimeMillis();
                if (videoCall) {
                    setVideoMute(false);
                    startSendingKeyFrame();
                }

                // check whether the 183 has arrived or not
            } else if (callState == pjsip_inv_state.PJSIP_INV_STATE_EARLY){

**Comment by ck505778675** [comment]
BTW ,error occurs but the audio data  transport  is ok

**Comment by ck505778675** [comment]
thanks ! problem has been solved!

**Comment by aenonGit** [comment]
What was the problem?

**Comment by SachithKasthuriarachchi** [comment]
Hi, same issue. could you please tell me how you solved it? @ck505778675

**Comment by natansalda** [comment]
hi I have the same problem, would appreciate info what was the issue :)
