### ISSUE TITLE
How to config when I want to call a  1080p video

### ISSUE THREAD

**Issue by ck505778675** [VoiSmart/pjsip-android#101]
as title;

**Comment by aenonGit** [comment]
You can call any recipient BUT the library will always encode/decode as low resolution. It is hardcoded for now but I plan to make it configurable from the outside. That should be preceded by an update to the openh264 lib

**Comment by ck505778675** [comment]
is there any interface to send the encoded stream ;

**Comment by ck505778675** [comment]
> is there any interface to send the encoded stream ;

@aenonGit

**Comment by aenonGit** [comment]
What?

**Comment by ck505778675** [comment]
> What?

encode video outside of pjsip and translate by pjsip

**Comment by aenonGit** [comment]
Not at the state of the art. The stream must be captured by pjsip itself

**Comment by ck505778675** [comment]
> Not at the state of the art. The stream must be captured by pjsip itself

oh!! how we can use hardcode to encode the hd video ,soft encode is always stuck!

**Comment by aenonGit** [comment]
You can try changing the hardcoded video resolution values in SipServiceConstants to fit your needs. But as it is untested I'm not sure it will work

**Comment by ck505778675** [comment]
> You can try changing the hardcoded video resolution values in SipServiceConstants to fit your needs. But as it is untested I'm not sure it will work

I  changed profile-level-id to 42e029 ,maxbps to 68000000 , but not ok

**Comment by aenonGit** [comment]
But that's not what I told u man. If your problem is transmitting and/or receiving a 1080p stream and encode/decode it with that resolution, you can try changing the values I suggested. Otherwise dunno how to help.

**Comment by ck505778675** [comment]
OK，thanks！
