### ISSUE TITLE
During ongoing call If I turned off the Wifi (No internet) The call still connected.

### ISSUE THREAD

**Issue by mudassirzulfiqar** [VoiSmart/pjsip-android#102]
Im facing an issue that If Im in the call with someone and internet goes off (WiFi off). The library waits for at least 20 to 30 seconds for generating the 408 :PJSIP_SC_REQUEST_TIMEOUT. This behaviour is somehow not suitable for client side app, because the client should immediately see this PJSIP_SC_REQUEST_TIMEOUT may be after 10 seconds.

Can anyone please tell me how I can change this interval to my required time.

**Comment by aenonGit** [comment]
Dunno about that but "immediately" it's impossible, that's not how it works. But, on the app client side, you can just listen for the network availability and drop the call as required
