### ISSUE TITLE
unable to sync libopenh264.so for x86

### ISSUE THREAD

**Issue by KousalyaT** [VoiSmart/pjsip-android#105]
When I try add "libopen264.so" Getting "file was loaded in wrong encoding: 'UTF-8' " 
![openh264](https://user-images.githubusercontent.com/66105798/83223612-e6f2e380-a198-11ea-8713-44f30e23404f.png)

**Comment by jackkum** [comment]
What for you opening binary file as text?

**Comment by KousalyaT** [comment]
> What for you opening binary file as text?

I have downloaded libopenh264.so and libpjsua2.so for x86 abi. when I tried to paste it in my code under jnilibs, I got error only in libopenh624.so.

**Comment by jackkum** [comment]
No, at least you need to add this part of code
https://github.com/VoiSmart/pjsip-android/tree/master/sipservice/src/main/java/org/pjsip

**Comment by KousalyaT** [comment]
I already have arm64-v8a, armeabi-v7a and armeabi jni for my code. But now I need x86 also. So I thought x86 in this project will help. But now I am clear that need to generate seperate one for my code. here is my question in stack https://stackoverflow.com/q/61658710/11630822. If you can give any ideas for this issue, then it will be very helpful for me. Also I am closing my issue.

**Comment by jackkum** [comment]
Linker can't find method `TransportConfig_EncryptionType_set` this is, possible, because you have a different version of libpjsua2, as i remeber 2.6 in this repository, maybe i'am wrong. Try compile the same version as you had for different architicture.
