### ISSUE TITLE
How to disable camera access when init endpoint?Please

### ISSUE THREAD

**Issue by phanpiseth9** [VoiSmart/pjsip-android#106]
PJSIP has access camera device so when service just start it make camera popup (like Oppo Reno).
How to disable it Please help.

**Comment by aenonGit** [comment]
You should disable video support when building pjsip [here](https://github.com/VoiSmart/pjsip-android-builder).

**Comment by aenonGit** [comment]
if you instead just want to get rid of the device popup, which I'm guessing pops when the app is not in foreground (security stuff) you need to execute the initialization of the endpoint inside a foreground service

**Comment by phanpiseth9** [comment]
> You should disable video support when building pjsip [here](https://github.com/VoiSmart/pjsip-android-builder).

So cannot disable video support by Java API? Okay need me disable it and rebuild.
Thanks you for your reply...

**Comment by phanpiseth9** [comment]
> if you instead just want to get rid of the device popup, which I'm guessing pops when the app is not in foreground (security stuff) you need to execute the initialization of the endpoint inside a foreground service

I have start service in foreground already.. i think when all app access Camera so device (like oppo Reno) it will pop camera on.

**Comment by aenonGit** [comment]
I had same problem wit samsung device, which alerted about camera and mic being accessed in background, but by using a foreground service (with notification icon) it disappeared. Anyway you sould be good by removing video support ... unless you need that support

**Comment by phanpiseth9** [comment]
> I had same problem wit samsung device, which alerted about camera and mic being accessed in background, but by using a foreground service (with notification icon) it disappeared. Anyway you sould be good by removing video support ... unless you need that support

Yes I'm no need video support.

**Comment by phanpiseth9** [comment]
hello please help me
i was build and not yet change everything but when use it error like this.

java.lang.NoSuchMethodError: no static method "Lorg/pjsip/pjsua2/pjsua2JNI;.SwigDirector_Buddy_onBuddyEvSubState(Lorg/pjsip/pjsua2/Buddy;J)V"
        at org.pjsip.pjsua2.pjsua2JNI.swig_module_init(Native Method)
        at org.pjsip.pjsua2.pjsua2JNI.<clinit>(pjsua2JNI.java:2509)
        at org.pjsip.pjsua2.pjsua2JNI.new_Endpoint(Native Method)
        at org.pjsip.pjsua2.Endpoint.<init>(Endpoint.java:68)

**Comment by aenonGit** [comment]
let me know if you managed to to that
