### ISSUE TITLE
Parameter for setHost()

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [VoiSmart/pjsip-android#108]
Hi, I am developing an android application using the VoiSmart/pjsip-android. In there to register an account we need to provide username, password, realm and host for the account. For example let's assume my sip account is on linphone server, and
username = sachith
password = 12345
realm = sip.linphone.org
host = ?

Could you please clarify what should I input for host? Is it the IP address of the mobile phone running my android app? or is it something to do with the server?

**Comment by mudassirzulfiqar** [comment]
host = sip.linphone.org in your case

**Comment by SachithKasthuriarachchi** [comment]
thank you very much
