### ISSUE TITLE
The onIncomingCall(), onOutgoingCall() methods never get triggered

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [VoiSmart/pjsip-android#111]
Hi, I am developing a mobile app based on this library and I have extended the BroadcastEventReceiver and has it registered in the MainActivity. But, the only method triggers in that extended class in the 'onCallState()' method. Could you please solve me this issue?

**Comment by mudassirzulfiqar** [comment]
Please insert your code.

**Comment by SachithKasthuriarachchi** [comment]
In my manifest file I declared my extended receiver and the SipService.
`<service
            android:name=".core.SipService"
            android:enabled="true"
            android:exported="true" />`

`<receiver
            android:name=".impl.Receiver"
            android:enabled="true"
            android:exported="true">
            <intent-filter>
                <action android:name=".core.BroadcastEventEmitter.BroadcastAction.OUTGOING_CALL" />
                <action android:name=".core.BroadcastEventEmitter.BroadcastAction.INCOMING_CALL" />
            </intent-filter>
        </receiver>`

My Receiver.class looks like follows.

![image](https://user-images.githubusercontent.com/44407066/88570651-0eabde00-d05a-11ea-8ac3-bf61556a4cfc.png)
![image](https://user-images.githubusercontent.com/44407066/88570687-1e2b2700-d05a-11ea-9a1e-a86ec67aa2ed.png)
![image](https://user-images.githubusercontent.com/44407066/88570717-2c794300-d05a-11ea-90e1-c21b54e4fdda.png)

In my MainActivity, I register the receiver by calling,

`receiver.register(getApplicationContext());`

But, the onIncomingCall() or onOutgoingCall() never triggered. Instead only triggering one is onCallState(). I checked the BroadcastEventEmitter class and it really emit the intents related to incoming and outgoing call. But, it seems like the BroadcastEventReceiver not catching them. 

I appreciate your help

**Comment by SachithKasthuriarachchi** [comment]
I solved this issue by changing the intent emitting methods in the incomingCall and outgoingCall in the BroadcastEventEmitter class as,

`mContext.sendBroadcast(intent);`
