### ISSUE TITLE
Getting '120013  - Permission denied' error after upgrading to PJSIP 2.10 version

### ISSUE THREAD

**Issue by tushar-patil-android** [VoiSmart/pjsip-android#116]
After upgrading to PJSIP 2.10 version not able to make calls, getting below error while initiating call.

java.lang.Exception: Title:       pjsua_init(&ua_cfg, &log_cfg, &med_cfg)
Code:        120013
Description: Permission denied
Location:    ../src/pjsua2/endpoint.cpp:1701

Please help me with this.
Are you planning to upgrade this project to PJSIP 2.10 version?

**Comment by aenonGit** [comment]
I will but don't have a timeline yet
