### ISSUE TITLE
Direct calls - Account not removed on hangup

### ISSUE THREAD

**Issue by anonymous-one** [VoiSmart/pjsip-android#118]
Not sure if you are doing any further development on this, but I have been working on something for a week or so with your library and have found a number of bugs. Ill post a couple here as they popup and I have time.

When making direct calls, on hangup (or other call terminating issues), the guest account that invokes the call is not removed.

After 3 or 4 calls (call -> hangup, repeat), PJSIP will complain that there are "too many objects of this type".

**Comment by aenonGit** [comment]
I appreciate your bugging reports. Look forward to see them :)

On this specific one, I agree that the guest account are not cleared after call end. But they since they are volatile, I do not persist them I din't think it could be a problem. Beside that I've tried 10 calls generating 10 different guest accounts and nothing happened, no errors on the pjsip side

**Comment by aenonGit** [comment]
As a workaround have you can try restarting the lib as it will clear all the accounts, keeping only the configured ones

**Comment by mudassirzulfiqar** [comment]
@anonymous-one the same error I also faced, this happened in my case If I send register account and unregister request simultaneously, this is not the library end issue.

**Comment by anonymous-one** [comment]
Warning : I have been playing with android development for about 2 weeks now. This is the first for personal use project I took on. I own a SIP based door intercom, which I now stream / communicate with via a tablet hung on my wall. Working great so far!

---

I can replicate this with fairly easy consistency. All it takes is hammering on the call / hangup button for a few seconds and pjsip will spit out a "too many objects". I dont have the paste available as I have a fix in place, but here is what I did... Warning, this should be expanded a bit for those who direct call multiple / different targets. Since I only have one target (the Doorbird intercom downstairs), it works for me.

In ```SipService.java - private void handleMakeDirectCall(Intent intent)``` I added the following:

```
if (mConfiguredGuestAccount == null) {
                SipAccount pjSipAndroidAccount = new SipAccount(SipService.this, sipAccountData);
                pjSipAndroidAccount.createGuest();
                mConfiguredGuestAccount = pjSipAndroidAccount;
                mActiveSipAccounts.put(accountID, pjSipAndroidAccount);
            } else {
                mActiveSipAccounts.put(accountID, mConfiguredGuestAccount);
            }
```

I'm sure you can tell, but essentially its recycling the previously set mConfiguredGuestAccount if one is available.

Like I said, would be worth checking at minimum the URI to see if they match, and go from there.

**Comment by anonymous-one** [comment]
Not to send any unnecessary checks your way, but maybe try call -> hangup to the same target, quickly (Eg: as fast as the finger will move ;)). That is when it occurred for me.

Eventually pjsip clears those objects (on GC?) but it took some time before I could make another call.

> I appreciate your bugging reports. Look forward to see them :)
> 
> On this specific one, I agree that the guest account are not cleared after call end. But they since they are volatile, I do not persist them I din't think it could be a problem. Beside that I've tried 10 calls generating 10 different guest accounts and nothing happened, no errors on the pjsip side

**Comment by anonymous-one** [comment]
The final solution which I have settled on is:

```
            if( mConfiguredGuestAccount!=null ){
                mConfiguredGuestAccount.delete();
                mConfiguredGuestAccount = null;
            }
            mConfiguredGuestAccount = new SipAccount(SipService.this, sipAccountData);
            mConfiguredGuestAccount.createGuest();
            mActiveSipAccounts.put(accountID, mConfiguredGuestAccount);
```
