### ISSUE TITLE
Could you please provide any sample app?

### ISSUE THREAD

**Issue by danek130995** [VoiSmart/pjsip-android#121]
Hello guys! A am new to the SIP, i need to create a voice calling app. Could you please provide with some sample app showing how to use this library? Thank you.

**Comment by fengfeilong0529** [comment]
The same question. I have completed the basic functions, but the other party’s video is displayed in green during the call. How can I solve this? Thanks for answer.

**Comment by lahirutm** [comment]
Please check here: https://blogs.webservice.lk/2021/03/10/simple-sip-voip-android-app-using-pjsip-library/  will provide the detailed documentation later.

**Comment by aenonGit** [comment]
samples from the official repo can be found here, it is trivial to apply to this

https://github.com/pjsip/pjproject/tree/master/pjsip-apps/src/swig/java
