### ISSUE TITLE
SIP Autorization Headers Missing in INVITE

### ISSUE THREAD

**Issue by lahirutm** [VoiSmart/pjsip-android#125]
Hi, I am using pjsip library 2.6 version in a old app and this  VoiSmart /pjsip-android  (PJSIP version 2.8) in a new app. I am facing an issue in  VoiSmart /pjsip-android. But old app which is using 2.6 version is working fine. Then i checked the PCAP files for both call log  and found below difference.

PJSIP Version 2.6
-------------------------
Request-Line: INVITE sip:94777730889@178.255.40.2 SIP/2.0
        Method: INVITE
        Request-URI: sip:94777730889@178.255.40.2
            Request-URI User Part: 94777730889
            Request-URI Host Part: 178.255.40.2
        [Resent Packet: False]

 VoiSmart /pjsip-android (PJSIP Version 2.8)
 ---------------------------------------------------------
Request-Line: INVITE sip:94777730889@178.255.40.2 SIP/2.0

INVITE section receiving more parameters to server side from the app using pjsip 2.6 library. But in the App usibg  VoiSmart /pjsip-android is sending only single line to the server and it is rejecting.

Anyone have an idea for this ?

**Comment by mudassirzulfiqar** [comment]
Im facing the same issue.

**Comment by aenonGit** [comment]
this library has pjsip 2.8, it means you have rebuild pjsip and included here. I can't handle all the incompatibilities or changes that needs to be done on each pjsip versions. Closing for now until I have the change to update the pjsip lib version
