### ISSUE TITLE
Having some trouble registering a sip account

### ISSUE THREAD

**Issue by SomeKoder** [VoiSmart/pjsip-android#131]
I have Wireshark running so that I can monitor the packets and ordering. What I'd expect to see while registering is:

    Me -> Request: REGISTER
    Server -> 401 Unauthorized
    Me -> Request: REGISTER
    Server -> 200 OK

This is not what is happening in my case though, this is what is happening for me:

    Me -> Request: REGISTER
    Me -> Request: REGISTER
    Server -> 401 Unauthorized
    Server -> 401 Unauthorized

Here is my android code:

    val sipAccount = SipAccountData()
    sipAccount.authenticationType = AUTH_TYPE_DIGEST
    sipAccount.username = sipCredentials.userName
    sipAccount.password = sipCredentials.password
    sipAccount.host = sipCredentials.host
    sipAccount.realm = sipCredentials.realm

    val accountId = SipServiceCommand.setAccount(applicationContext, sipAccount)

I'm aware there's no support for this library, but I'm hoping I can get some help for this issue.

Thanks in advance!

**Comment by SomeKoder** [comment]
Update: After some further investigation, I'm only getting back:

    Me -> Request: REGISTER
    Server -> 401 Unauthorized

I do get a nonce in the server response, I'm still not sure why it's not attempting to register again... I'll keep updating this thread if I find new information.

**Comment by aenonGit** [comment]
you could try enabling the pjsip logs (check the official pjsip kotlin app on their GitHub repo for the code)

**Comment by mudassirzulfiqar** [comment]
@SomeKoder can you post the pjsip logs, For registration flow , I had the same issues before

**Comment by SomeKoder** [comment]
@aenonGit , @mudassirzulfiqar 

I enabled logs for pjsip, and from what I can tell, the last error that occurs before pjsip starts destroying all of it's components it this:
    
    Unable to set auth for tdta0x6f41bb01b8: can not find credential for abc.com/Digest

At this point, PJSIP starts to shutdown everything.

**Comment by SomeKoder** [comment]
Update:
When setting my realm to "*", I get this:

    Registration sent
    Destroying...
Then pjsua shuts down without getting a response.

If I set my realm to the same thing as my host, I get the same error as my previous comment:

    Unable to set auth for tdta0x6f41bf15c8: can not find credential for abc.com/Digest
    No suitable credential (PJSIP_ENOCREDENTIAL) [status=171101]

**Comment by lahirutm** [comment]
if you problem is related to Registration issue, please check this source. Registration is working without any issue in this source. But call dialing and receiving have an issue. https://github.com/lahirutm/SIP-Dialer

**Comment by SomeKoder** [comment]
I got it working by setting realm as "*"  in getAuthCredInfo, and keeping realm as "abc.com" in getIdUri. But I feel like this is a work around and not actually a fix. Because now I'm getting when attempting to call:

    407 Proxy Authentication Required

What do you guys think?

**Comment by lahirutm** [comment]
I am using settings like this.

        mAccount = new SipAccountData();
        mAccount.setHost("sipdoamin.com");
        mAccount.setRealm("*");
        mAccount.setPort(5060);
        mAccount.setUsername("123456");
        mAccount.setPassword("abcdef");
        mAccountId = SipServiceCommand.setAccount(this, mAccount);

Then when dialing an extention, "**@sipdoamin.com**"  part added end of the extension. 

        String callNumber = mEtCallNumer.getText().toString().trim() **+ "@sipdoamin.com"** ;
        
        try {
            SipServiceCommand.makeCall(this, mAccountId, callNumber, false, false);
        } catch (Exception e) {
            e.printStackTrace();
        }

I think it will resolve your problem.

**Comment by lahirutm** [comment]
> Update:
> I seem to have everything working correctly now. what fixed it was a combination of what I posted earlier in the thread. And for calling, I just switched account and all seems good now. Thank you @aenonGit , @mudassirzulfiqar and @lahirutm for your help!
> I will go ahead and close this issue.

Is this with latest release of VoiSmart/pjsip-android ? if yes, is it possible to share me the code parts ? I am still stuck with the call part. I have posted another issue for this.

**Comment by SomeKoder** [comment]
@lahirutm Indeed it's the latest version, it didn't work on my test account but my production account worked fine with this code:
  
SipAccountData.java:

    AuthCredInfo getAuthCredInfo() {
        return new AuthCredInfo(authenticationType, "*", username, 0, password); // Hardcoding realm as "*"
    }
    
Registration:

        val sipAccount = SipAccountData()
        sipAccount.authenticationType = AUTH_TYPE_DIGEST
        sipAccount.username = userId
        sipAccount.password = password
        sipAccount.host = realm
        sipAccount.realm = realm

        sipAccountId = SipServiceCommand.setAccount(applicationContext, sipAccount)

Calling:

    SipServiceCommand.makeCall(requireContext(), sipAccountId, _binding.editTextPhone.text.toString(), false, false)
