### ISSUE TITLE
In BroadcastReceiver -> onIncomingCall event is not receiving when call coming.

### ISSUE THREAD

**Issue by lahirutm** [VoiSmart/pjsip-android#133]
In BroadcastReceiver -> onIncomingCall event is not receiving when call coming. Only the onCallState receiving.
Here is the log

```
D/SipAccount: Added incoming call with ID 0 to sip:47419
D/SipAccount: Sending 180 ringing
D/SipServiceBR: onCallState - accountID: sip:47419, callID: 0, callStateCode: 2, callStatusCode: 100, connectTimestamp: 0, isLocalHold: false, isLocalMute: false, isLocalVideoMute: false
D/SipServiceBR: onCallState - accountID: sip:47419, callID: 0, callStateCode: 3, callStatusCode: 180, connectTimestamp: 0, isLocalHold: false, isLocalMute: false, isLocalVideoMute: false
D/SipAccount: Removing call with ID: 0
D/SipServiceBR: onCallState - accountID: sip:47419, callID: 0, callStateCode: 6, callStatusCode: 487, connectTimestamp: 0, isLocalHold: false, isLocalMute: false, isLocalVideoMute: false
```

In Previous version it is coming as expected. Issue is in the new version.

Also Outgoing call is not woring CallStatusCode: 0 always.

**Comment by aenonGit** [comment]
most likely it's because of this 08fe56404b2b650d9cc91b628c667ca344eb6f7e : the namespace has changed

**Comment by lahirutm** [comment]
But this is broadcasting
D/SipServiceBR: onCallState 
Anyway how to resolve the issue, can i change the namespace in BroadcastEventEmitter.java back to "net.gotev" ?
Also please drop me an email (lahirutm@gmail.com), if you like to give me a support, i will pay for it. i want to develop a simplae sip client with G729.

**Comment by aenonGit** [comment]
can you post the SIP packets exchanged? Besides you could also try to comment out this in SipAccountData

```
// nat configs to allow call reconnection across networks
accountConfig.getNatConfig().setSdpNatRewriteUse(pj_constants_.PJ_TRUE);
accountConfig.getNatConfig().setViaRewriteUse(pj_constants_.PJ_TRUE);
```

**Comment by lahirutm** [comment]
Thank You for your support, But it didn't work for the issue. Please find the attached pcap file for SIP packets exchanged.
[pjsip1.pcap.txt](https://github.com/VoiSmart/pjsip-android/files/6650243/pjsip1.pcap.txt)

**Comment by lahirutm** [comment]
Resolved the issue by commenting out and putting this in BroadcastEventEmitter.Java

//sendExplicitBroadcast(intent);
 mContext.sendBroadcast(intent);

**Comment by aenonGit** [comment]
> Resolved the issue by commenting out and putting this in BroadcastEventEmitter.Java
> 
> //sendExplicitBroadcast(intent);
>  mContext.sendBroadcast(intent);

I use a manifest level receiver which requires that type of broadcast but I could use the implicit broadcast as a fallback in case the explicit one fails. Have you noted if it was failing (return false) ?

**Comment by lahirutm** [comment]
> > Resolved the issue by commenting out and putting this in BroadcastEventEmitter.Java
> > //sendExplicitBroadcast(intent);
> > mContext.sendBroadcast(intent);
> 
> I use a manifest level receiver which requires that type of broadcast but I could use the implicit broadcast as a fallback in case the explicit one fails. Have you noted if it was failing (return false) ?

Looks like it is not returning anything, i will check more. Incoming call issue sorted out as mentioned above, but i am still having the issue with outgoing calls (It is not related to the broadcasting). Call is not going to server side.

This is the Run Log.
D/SipAccount: New outgoing call with ID: 0
D/SipServiceBR: onCallState - accountID: sip:123456@sipdomain.com, callID: 0, callStateCode: 1, callStatusCode: 0, connectTimestamp: 0, isLocalHold: false, isLocalMute: false, isLocalVideoMute: false
D/SipServiceBR: onOutgoingCall - accountID: sip:123456@sipdomain.com, callID: 0, number: 0094716008543
D/SipServiceBR: onCallState - accountID: sip:123456@sipdomain.com, callID: 0, callStateCode: 6, callStatusCode: 408, connectTimestamp: 0, isLocalHold: false, isLocalMute: false, isLocalVideoMute: false
D/SipServiceBR: onCallState - accountID: sip:123456@sipdomain.com, callID: 0, callStateCode: 6, callStatusCode: 408, connectTimestamp: 0, isLocalHold: false, isLocalMute: false, isLocalVideoMute: false
