### ISSUE TITLE
[Question] How do you guys handle incoming calls while app is terminated?

### ISSUE THREAD

**Issue by SomeKoder** [VoiSmart/pjsip-android#139]

**Comment by aenonGit** [comment]
You have two options:

1 easier but ugly and unreliable - asking the users to whitelist the app from being killed by the OS

2 harder but 99% reliable - using FCM notification to wake your app (and perform a sip register) before the sip invite arrives.

You can read something here https://developer.android.com/training/monitoring-device-state/doze-standby

**Comment by SomeKoder** [comment]
Thank you! I will check it out

**Comment by SomeKoder** [comment]
The issue I'm having is the notification being sent from the backend and the sip invite are arriving almost at the same time.

I'm not sure how I'm supposed to handle cases where the user might take a few seconds to accept the call either... Because by the time they click on the notification, the sip invite is long past. 

Would it be possible to have a code example? 

Here's what I got so far:

    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        super.onMessageReceived(remoteMessage)
        showIncomingCallNotification(remoteMessage.notification?.title)
    }

    private fun showIncomingCallNotification(title: String?){

        val customView = RemoteViews(packageName, R.layout.notification_incoming_call)
      
        val notificationIntent = Intent(this, MainActivity::class.java)
        val hangupIntent = Intent(this, BroadcastReceiver::class.java)
        val answerIntent = Intent(this, MainActivity::class.java)
      
        answerIntent.action = "ACCEPT"
        hangupIntent.action = "DECLINE"
      
        val pendingIntent = PendingIntent.getActivity(this, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT)
        val hangupPendingIntent = PendingIntent.getBroadcast(this, 0, hangupIntent, PendingIntent.FLAG_UPDATE_CURRENT)
        val answerPendingIntent = PendingIntent.getBroadcast(this, 0, answerIntent, PendingIntent.FLAG_UPDATE_CURRENT)
      
        customView.setOnClickPendingIntent(R.id.textViewAccept, answerPendingIntent)
        customView.setOnClickPendingIntent(R.id.textViewDecline, hangupPendingIntent)
        customView.setTextViewText(R.id.textViewTitle, title)
        customView.setTextViewText(R.id.textViewContent, "Incoming Call")
      
        val notification = NotificationCompat.Builder(this, INCOMING_CALL_CHANNEL_ID)
        notification.setSmallIcon(R.drawable.ic_call)
        notification.setDefaults(Notification.DEFAULT_LIGHTS or Notification.DEFAULT_SOUND)
        notification.setCategory(NotificationCompat.CATEGORY_CALL)
        notification.setVibrate(longArrayOf(1000, 1000, 1000, 1000))
        notification.setOngoing(true)
        notification.setFullScreenIntent(pendingIntent, true)
        notification.priority = NotificationCompat.PRIORITY_MAX
        notification.setStyle(NotificationCompat.DecoratedCustomViewStyle())
        notification.setCustomContentView(customView)
        notification.setCustomBigContentView(customView)
      
        startForeground(1124, notification.build())
    }

I'm not too sure about anything beyond displaying the notification at this point.

**Comment by aenonGit** [comment]
The server should at least wait some seconds before sending the invite to accommodate the registration to complete. Beside that the process should be automatic on client side, without the user to manually click on the notification imho.

Ideally the server should wait for the registration to complete before sending the invite.

**Comment by SomeKoder** [comment]
Alright, I'll try with this information. Thank you!

**Comment by SomeKoder** [comment]
I succeeded in getting things working. Not the most beautiful solution possible I'm sure, but functional. Thank you for guiding me in the right direction! Very much appreciate it!

    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        super.onMessageReceived(remoteMessage)

        val intent = Intent(this, CallForegroundService::class.java)
        startForegroundService(intent)
    }
    
    class CallForegroundService : Service() {

        private var callId: Int = 0
        private lateinit var ringtone: Ringtone
        private lateinit var vibrator: Vibrator
    
        private var callerName: String? = null
  
        override fun onCreate() {
            super.onCreate()
   
            callBroadcastReceiver.register(this)
        }
  
        override fun onDestroy() {
            super.onDestroy()
    
            callBroadcastReceiver.unregister(this)
        }
  
        override fun onBind(intent: Intent?): IBinder? {
            return null
        }
  
        override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    
            callerName = intent?.getStringExtra("calledName")
    
            val user = UserManager.getSipAccountId(this)
            SipServiceCommand.getRegistrationStatus(this, user)
    
            return START_NOT_STICKY
        }
  
        private fun showIncomingCallNotification(backupCallerName: String?){
    
            createIncomingCallNotificationChannel()
    
            val notificationIntent = Intent(this, MainActivity::class.java)
    
            notificationIntent.action = "INCOMING_CALL"
    
            val pendingIntent = PendingIntent.getActivity(this, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT)
    
            val notification = NotificationCompat.Builder(this, notificationChannelName)
                .setContentTitle("Incoming Call")
                .setContentText(callerName)
                .setSmallIcon(R.drawable.ic_call)
                .setOngoing(true)
                .setFullScreenIntent(pendingIntent, true)
                .setContentIntent(pendingIntent)
                .build()
    
            try {
                val r: Uri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE)
                ringtone = RingtoneManager.getRingtone(applicationContext, r)
                ringtone.play()
    
                vibrator = (this.getSystemService(VIBRATOR_SERVICE) as Vibrator)
                vibrator.vibrate(longArrayOf(1000, 1000, 1000, 1000), 0)
            } catch (e: Exception) {
                e.printStackTrace()
            }
    
            startForeground(notificationId, notification)
        }
    
        private var callBroadcastReceiver: BroadcastEventReceiver = object : BroadcastEventReceiver() {
    
            override fun onIncomingCall(event: IncomingCallEvent) {
                super.onIncomingCall(event)
    
                Timber.d("$TAG: onIncomingCall")
                callId = event.callID
                PreferenceManager.setLastCallId(this@CallForegroundService, callId, event.displayName ?: "???")
    
                showIncomingCallNotification(event.displayName)
            }
    
            override fun onCallState(event: CallStateEvent?) {
                super.onCallState(event)
    
                if (callId == event?.callID && event.callStateCode == 5){
                    ringtone.stop()
                    vibrator.cancel()
                }
                else if (callId == event?.callID && event.callStateCode == 6){
                    stopForeground(true)
                    ringtone.stop()
                    vibrator.cancel()
                }
            }
        }
    
        private fun createIncomingCallNotificationChannel() {
            val notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
            val notificationChannel = NotificationChannel(notificationChannelName, notificationChannelName, NotificationManager.IMPORTANCE_HIGH)
            notificationManager.createNotificationChannel(notificationChannel)
        }
    
        companion object {
            const val TAG = "CallForegroundService"
            private const val notificationId = 1123
            private const val notificationChannelName = "incomingCallChannel"
        }
