### ISSUE TITLE
"Not Acceptable here" Error while accepting the call

### ISSUE THREAD

**Issue by rahul-jain-7893** [VoiSmart/pjsip-android#14]
Error Logs - 
 pjsua_call_answer2(id, param.p_opt, prm.statusCode, param.p_reason, param.p_msg_data)
org.pjsip.pjsua2.app W/System.err: Code:        170488
org.pjsip.pjsua2.app W/System.err: Description: Not Acceptable Here
org.pjsip.pjsua2.app W/System.err: Location:    ../src/pjsua2/call.cpp:498

when at other end i am going to accept it.

**Comment by aenonGit** [comment]
Still facing it? It might be related to codec incompatibility. Which codecs are the parties offering?

**Comment by Adnan-addi** [comment]
Hi i am facing the same issue- video call works when received from ios and when received from android i face the same logs after answering the call. please help what could be possible reasons for this issue .
Thanks
