### ISSUE TITLE
Found an issue with userless account (getGuestAccountConfig)

### ISSUE THREAD

**Issue by ghost** [VoiSmart/pjsip-android#141]
In the SipAccountData.java, **getGuestAccountConfig()** has a line of code **accountConfig.getSipConfig().getProxies().add(getProxyUri());**. 

This will cause "gethostbyname() has returned error." when making a call with a userless account since the function try to find none-exist ProxyUri parameters from the account.

**Comment by aenonGit** [comment]
Well, it should not be that way, if you look at the code, if you want to use a `guest account` you need to call `makeDirectCall` which build the guest account with the required parameters. Those parameters will be also used to build all necessary data for that account.
