### ISSUE TITLE
Audio Conference Bridge

### ISSUE THREAD

**Issue by bovindev** [VoiSmart/pjsip-android#149]
How to realize the audio conference bridge, thank you

**Comment by jackkum** [comment]
if i right understand you, this should be implemented on the server side. 
Asterisk example:
sip.conf
```
[some-master]
type=friend
host=dynamic
context=master
; ...

[some-client]
type=friend
host=dynamic
context=client
; ...
```

extension.conf
```
[master]
exten => _X.,1,Answer()
exten => _X.,2,MeetMe(room-${EXTEN}, ACdkq)

[client]
exten => _X.,1,Answer()
exten => _X.,2,MeetMe(room-${EXTEN}, xqr)
```

So outgoing call to 123@host.sip with master credentials will create new room with name 123. Others clients should make call with client credentials and they will add to this room if it exists(until master in there). 

You can define rooms or create it dynamically. 
[Read more about MeetMe function and arguemnts.](https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+Application_MeetMe)

**Comment by bovindev** [comment]
Thank you for your answer,this is not the case, such as A->B, A->C. Then start the conference A->B->C->B. Three parties can talk

**Comment by jackkum** [comment]
@bovindev Approximate solution would looks like:

extenstion.conf
```
[client]
exten => B,1,Dial(SIP/B,,G(callback,s,1))
exten => C,1,Dial(SIP/C,,G(callback,s,1))
exten => R,1,MeetMe(roomName, ...)

[callback]
; caller will go to end
exten => s,1,Goto(s,3)
; callee will go to the room
exten => s,2,MeetMe(roomName, ...)
; hangup caller
exten => s,3,Hangup()
```
Steps:
1. Call to B@host.sip and wait hangup
2. Call to C@host.sip and wait hangup
3. Call to R@host.sip and talk

[Example: Dial into ConfBridge using 'G' option](https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Application_Dial)

**Comment by aenonGit** [comment]
As you can see from the readme, conference calls are not supported yet. Closing for now
