### ISSUE TITLE
Bluetooth Headset

### ISSUE THREAD

**Issue by waheedkhan-dev** [VoiSmart/pjsip-android#151]
I have faced the problem related to Bluetooth Headset is anyone have a solution how to connect Bluetooth headset with PJSIP Call properly, for now on some headsets I hear the voice but side B does not hear my voice properly. My voice passes through phone speakers instead of Headsets speakers. One more thing in some cases some headsets connect and some do not.

**Comment by ghost-recone** [comment]
I have fixed the problem it's was not related to PJSUA. Just minor changes in AudioManager configurations fixed the problem.

**Comment by aenonGit** [comment]
If you could please share the fix so that to help others. I will then close the issue

**Comment by aenonGit** [comment]
@waheedkhan-dev
