### ISSUE TITLE
BYE not received

### ISSUE THREAD

**Issue by aenonGit** [VoiSmart/pjsip-android#186]
PJSIP_TRANSPORT_IDLE_TIME is by default set to 33 seconds, if OPTIONS or any other SIP message is not received for every 33 seconds window, the transport will be shutdown causing any subsequent received SIP message to be lost (never actually received).

This usually happens when servers do not send OPTIONS for non registered users (using the guest account)

**Comment by kukadiyaAni** [comment]
@aenonGit was your issue fixed? I used the latest code and still get the same issue, I'm using UDP

**Comment by aenonGit** [comment]
In recent releases this specific scenario has been fixed by increasing the idle time to 600, you can read more about it in the builder repo

**Comment by kukadiyaAni** [comment]
@aenonGit as I see PJSIP_TRANSPORT_IDLE_TIME it's for TCP/TLS but I'm using UDP is there the same PJSIP_TRANSPORT_IDLE_TIME used for UDP?

**Comment by aenonGit** [comment]
UDP is connectionless, so I guess no

**Comment by kukadiyaAni** [comment]
BYE was not received after 33 seconds with UDP, Do you know any option to fix this issue
