### ISSUE TITLE
remove video support and add 64bit arch

### ISSUE THREAD

**Issue by aenonGit** [VoiSmart/pjsip-android#19]
When making audio-only calls the library negotiates video codecs too in the SDP. This causes some troubles with PBX like FreeSwitch.

**Comment by hthetiot** [comment]
Using branch "fix_19_remove_video_support_and_add_64bit_support" and by fixing disabled codec in MainActivity.java I was able to perform call on FreeSwitch.

Thanks @aenonGit 

```
- codec.setPriority(CodecPriority.PRIORITY_DISABLED);
+ codec.setPriority(CodecPriority.PRIORITY_MAX - 1);
```
- https://github.com/VoiSmart/pjsip-android/blob/master/examples/demoapp/app/src/main/java/net/gotev/sipservicedemo/MainActivity.java#L51

**Comment by navylkh** [comment]
ㅈㅉ

2017. 12. 24. 오전 7:19에 "Harold Thétiot" <notifications@github.com>님이 작성:

**Comment by omar-othmann** [comment]
x86 has text relocations
