### ISSUE TITLE
Ignored error on setting window flags on wid=1: Invalid or unsupported video capability (PJMEDIA_EVID_INVCAP)

### ISSUE THREAD

**Issue by zhoyu123123123** [VoiSmart/pjsip-android#194]
I/System.out: 19:34:30.368            pjsua_vid.c  Starting preview for cap_dev=-1, show=1
I/System.out: 19:34:30.368            pjsua_vid.c  .Creating video window: type=preview, cap_id=-1, rend_id=-2
I/System.out: 19:34:30.368            pjsua_vid.c  ..Window already exists for cap_dev=-1, returning wid=1
I/System.out: 19:34:30.369            pjsua_vid.c  ..Ignored error on setting window visibility on wid=1: Invalid or unsupported video capability (PJMEDIA_EVID_INVCAP)
I/System.out: 19:34:30.369            pjsua_vid.c  ..Ignored error on setting window flags on wid=1: Invalid or unsupported video capability (PJMEDIA_EVID_INVCAP)

**Comment by aenonGit** [comment]
close for inactivity
