### ISSUE TITLE
[ISSUE] Crash BroadcastReceiver SecurityException

### ISSUE THREAD

**Issue by TienHai** [VoiSmart/pjsip-android#199]
Hi

I have this crash after start PJSIP :

Caused by: java.lang.SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

Lib version
 2.12.1

project Compile SdkVersion = 34

Smartphone (please complete the following information):

Device: Android
OS: 14

Tien Haï

**Comment by aenonGit** [comment]
Hi, I think it's related to new requirements of api 34. Will look into it as soon as I update the lib. Thanks for reporting. btw you should be able to easily fix it yourself on your end

**Comment by aenonGit** [comment]
@TienHai you can try out the latest develop
