### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by gotev** [VoiSmart/pjsip-android#2]
Sometimes random crashes occurs at startup. This is the log in LogCat:

```
../src/pjsua-lib/pjsua_acc.c:2848: pjsua_acc_find_for_incoming: assertion "pjsua_var.acc_cnt!=0" failed
Fatal signal 6 (SIGABRT), code -6 in tid 13567 (Thread-14107)
```

It may be the same problem described here: http://stackoverflow.com/questions/24877824/how-to-avoid-pjsua-assertion-failure-on-startup-race-condition but some further investigation is required

**Comment by cxrod** [comment]
I'm following your code (nice job btw) to understand how pjsua2 works. This error happend to me when i call ACTION_SET_ACCOUNT, then ACTION_REMOVE_ACCOUNT and ACTION_SET_ACCOUNT again. I'm investigating how to fix it.

**Comment by lw520will** [comment]
Hey I have got sloved this problems,and I haven't refresh my code on Github for so long.I will refresh my code after this days,and you can use it ！😄


发自网易邮箱大师
On 09/28/2016 00:28, Cesar Jose Rodriguez Diaz wrote:

I'm following your code (nice job btw) to understand how pjsua2 works. This error happend to me when i call ACTION_SET_ACCOUNT, then ACTION_REMOVE_ACCOUNT and ACTION_SET_ACCOUNT again. I'm investigating how to fix it.

**Comment by lw520will** [comment]
And btw thank you 😊


发自网易邮箱大师
On 09/28/2016 21:33, lw520will wrote:
Hey I have got sloved this problems,and I haven't refresh my code on Github for so long.I will refresh my code after this days,and you can use it ！😄


发自网易邮箱大师
On 09/28/2016 00:28, Cesar Jose Rodriguez Diaz wrote:

I'm following your code (nice job btw) to understand how pjsua2 works. This error happend to me when i call ACTION_SET_ACCOUNT, then ACTION_REMOVE_ACCOUNT and ACTION_SET_ACCOUNT again. I'm investigating how to fix it.
