### ISSUE TITLE
 running the project in android 

### ISSUE THREAD

**Issue by sureshacs17** [VoiSmart/pjsip-android#205]
Please let me know if there is any android UI application to test this service capabilities.

**Comment by sureshacs17** [comment]
Also please provide the steps to run this service on an android phone if available. Thanks

**Comment by xiezhouyan1027** [comment]
https://docs.pjsip.org/en/latest/get-started/android/build_instructions.html

**Comment by aenonGit** [comment]
samples from the official repo can be found here, it is trivial to apply to this

https://github.com/pjsip/pjproject/tree/master/pjsip-apps/src/swig/java
