### ISSUE TITLE
[BUG] Voice distortion.

### ISSUE THREAD

**Issue by askarsyzdykov** [VoiSmart/pjsip-android#208]
**Describe the bug**
I'm using SIP sample app. The mic's sound of whole operating system is changed after call via the sample app (see the attached video). Even if I open another app (e.g Mic test), the sound remain as on the video.

**Lib version**
2.12.1

**Smartphone (please complete the following information):**
 - Sony Android TV with 

 - OS: Android 9

https://github.com/VoiSmart/pjsip-android/assets/3222305/2808210d-f39f-4545-978b-d1c17e70bb04

**Comment by aenonGit** [comment]
which sample app are you talking about? Besides, the lib has never been tested or intended to be used with android tv.

Closing.

Feel free to reopen with additional information
