### ISSUE TITLE
Crach on x86 on start. Error libpjsua2.so: has text relocations

### ISSUE THREAD

**Issue by alexmelnikov** [VoiSmart/pjsip-android#21]
E/linker: /data/app/ru.naumen.naumenphone-1/lib/x86/libpjsua2.so: has text relocations
D/SIP Manager: UnsatisfiedLinkError: dlopen failed: /data/app/ru.mycompany.mycompany-1/lib/x86/libpjsua2.so: has text relocations
E/art: No implementation found for void org.pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ru.naumen.naumenphone, PID: 3922
                  java.lang.UnsatisfiedLinkError: No implementation found for void org.pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__)
                      at org.pjsip.pjsua2.pjsua2JNI.swig_module_init(Native Method)
                      at org.pjsip.pjsua2.pjsua2JNI.<clinit>(pjsua2JNI.java:2601)
                      at org.pjsip.pjsua2.pjsua2JNI.new_Endpoint(Native Method)
                      at org.pjsip.pjsua2.Endpoint.<init>(Endpoint.java:0)

**Comment by datso** [comment]
I've found that these relocations are added by openssl. You should rebuild the library and set "no-asm" parameter in openssl configure args.
Check https://github.com/datso/react-native-pjsip-builder/blob/master/android/build_openssl.sh for example.

**Comment by alexmelnikov** [comment]
datso, thank you! It's solution does work!

**Comment by omar-othmann** [comment]
@alexmelnikov can you upload them?
