### ISSUE TITLE
x86 has text relocations

### ISSUE THREAD

**Issue by omar-othmann** [VoiSmart/pjsip-android#24]
i can't run pjsip-android on android 6, error type: x86 has text relocations

can some one help me?

**Comment by FongMi** [comment]
https://code.google.com/archive/p/android-developer-preview/issues/3028

**Comment by aenonGit** [comment]
try out the new release and let me knoe @omar-othmann. haven't tested on x86 but I've followed the instruction to avoid the relocations

**Comment by omar-othmann** [comment]
I have fixed it

**Comment by aenonGit** [comment]
using the `no-asm` arg or else?

**Comment by omar-othmann** [comment]
else, if you want your jnilib work on api 21+
You need to change some file and edit it on libopenh, but it's not work on api 20-, you need to make like 2 apk one from api 16 - 20, one for api 20+

**Comment by omar-othmann** [comment]
Also, if you have old jnilib its work on api 16 to 20, upload it for me, and i upload for you 21+
