### ISSUE TITLE
Need Video Support Demo On Android

### ISSUE THREAD

**Issue by zhongjihao** [VoiSmart/pjsip-android#34]
I also install this site https://trac.pjsip.org/repos/wiki/Getting-Started/Android
I'm using PJSIP2.7.2, Openh264 has also been compiled
I have not compiled OpenSSL, I have just compiled "libpjsua2.so" & "libopenh264.so")
run Pjsua2 app has no video

Do not know whether or not to modify the pjsua2 app code to video calls, according to the official network compilation method does not come out, the trouble God to a latest version of pjsip compiled to support video calls Android platform code, my email zhongjihao100@163.com, very grateful

**Comment by aenonGit** [comment]
I will soon push some updates on the "testing_support_for_push_notification" branch to support video calls. Unfortunately it still uses some features for my use case. But you should be able to take that out ... everything related to the push notification support

**Comment by aenonGit** [comment]
samples of pjsip here https://github.com/pjsip/pjproject/tree/master/pjsip-apps/src/swig/java

closing, not strictly related to this repo
