### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by aenonGit** [VoiSmart/pjsip-android#35]

**Comment by ursusursus** [comment]
Hi, ive got a silly question, how do you know all this? pjsua2 guide doesnt include video afaik (http://www.pjsip.org/docs/book-latest/html/index.html)

**Comment by aenonGit** [comment]
@ursusursus I think that's a really outdated doc.

The starting point is [here](https://trac.pjsip.org/repos/wiki/Getting-Started/Android#VideoSupport) from there you can read the detailed doc about video support and doc [here](https://trac.pjsip.org/repos/wiki/Video_Users_Guide)

Hope it helps

**Comment by aenonGit** [comment]
@ursusursus check out the new releases of both repos and let me know. 

Closing

**Comment by ursusursus** [comment]
Docker for build? nice!

I want to ask you one more thing about video, In SipService you are hardcoding the `encFmt`, 
```
 MediaFormatVideo mediaFormatVideo = vidCodecParam.getEncFmt();
            mediaFormatVideo.setWidth(H264_DEF_WIDTH);
            mediaFormatVideo.setHeight(H264_DEF_HEIGHT);
            vidCodecParam.setEncFmt(mediaFormatVideo);
```

```
int H264_DEF_WIDTH = 640;
int H264_DEF_HEIGHT = 360;
```

Isn't this hardware dependant? If I try this on my nexus 5, i.e. look at camera api and list supported resoluitions, such is not present, and ends up with squished image. Same for back camera if you switch capture devices. Are you aware of this? Is this just best guess?

**Comment by aenonGit** [comment]
Sometimes I forget to "generalize" the library. That's a requirement of our video bridge, that's the fmt it uses and we align to it no matter what. But you can easily change it :)

**Comment by ursusursus** [comment]
Right, but if that fmt doesnt match any of available camera supported formats dictated by phone's hw, it will fail, no matter the bridge
