### ISSUE TITLE
Is there any solution for Call Conference ...

### ISSUE THREAD

**Issue by haraprasadsatapathy** [VoiSmart/pjsip-android#37]
Is there any solution for Call Conference ...

**Comment by aenonGit** [comment]
We have left that feature to be handled by the pbx (both audio and video conf)

**Comment by haraprasadsatapathy** [comment]
In C# .net this feature is there. Why we are not able to implement this feature.

**Comment by aenonGit** [comment]
simply because our pbx has already the support for conferencing and there's no need to implement it in the app side
