### ISSUE TITLE
Unable to receive incoming call when application in minimized position. Can,t able to call pjsip service in the service created by me. Please help

### ISSUE THREAD

**Issue by haraprasadsatapathy** [VoiSmart/pjsip-android#40]

**Comment by aenonGit** [comment]
could you please be more specific?

**Comment by Huu-Thai** [comment]
I have the same issue, I have created a always run service but don't know how to listen incoming call in it , anyone can help me ?

**Comment by aenonGit** [comment]
if you want to be able to receive calls in background, tou have few options:

- use FCM to wake your app (thus the sipservice) before receiving the SIP INVITE
- set the sipservice as a foregroundservice so it is always active (but might eventually be destroyed by the system). Then you can override the broadcastreceiver in your app to receive the incomingcall broadcast event
