### ISSUE TITLE
I wanna to know how to accept the call, please give some code snippet

### ISSUE THREAD

**Issue by guopengyu123** [VoiSmart/pjsip-android#49]
someone can help me?

**Comment by aenonGit** [comment]
this is the static method you should call:
`public static void acceptIncomingCall(Context context, String accountID, int callID)`

you should get the `callID` and `accountID` from the `BroadcastEventReceiver`

**Comment by cjcj125125** [comment]
When I receive a call, how do I distinguish between video and voice? thank you

**Comment by aenonGit** [comment]
when you override the broadcast receiver `onIncomingCall` there is the `isVideo` parameter.

```
public class CallReceiver extends BroadcastEventReceiver {

    @Override
    public void onIncomingCall(String accountID, int callID,
                               String displayName, String remoteUri,
                               boolean isVideo) {
        // do whatever you need to handle the incoming call
    }
}
```
