### ISSUE TITLE
not woking for Asterisk PBX

### ISSUE THREAD

**Issue by dehghanimeh** [VoiSmart/pjsip-android#6]
hi
this is a grate sample, i test is ,but not woking for Asterisk PBX server

**Comment by hthetiot** [comment]
Same with freeswitch due video see #19 , I will try the branches to see if it solve the issue.

**Comment by aenonGit** [comment]
try the push or prod branches, if you have problems with video you need to set the videoCount to 0 and send disabled media along the SDP (code in those branches when making a call in SipCall.java)

let me know
