### ISSUE TITLE
Jitpack builds failed

### ISSUE THREAD

**Issue by mocle** [VoiSmart/pjsip-android#60]
First a big compliment and praise for this great project!

It seems to me that the building process went wrong with the last 2 tags (2.0.0 and 2.0.1) at jitpack ([log file](https://jitpack.io/com/github/VoiSmart/pjsip-android/2.0.1/build.log)).
Now I don't seem to be able to integrate the current software version based on tags with maven and jitpack anymore.  The corresponding error message from the jitpack log:
```
* Where:
Build file '/home/jitpack/build/sipservice/build.gradle' line: 36

* What went wrong:
A problem occurred evaluating project ':sipservice'.
> Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Is it possible to fix the problem, or how else do I have to proceed to integrate the project module? Is there an example available?

**Comment by vipinkviswanath** [comment]
Is this solved? If not can you please show me the build.gradle?

**Comment by mocle** [comment]
The problems occur already with the current build.gradle of this project. Can you confirm this, or does the problem only affect jitpack and my loakle environment?
In my fork I updated Gradle and the Gradle google repositories.  

https://github.com/mocle/pjsip-android/commits/fix/jitpack-builds

With the adjustments it is now possible to build the module with Jitpack. But I'm not sure why the change is suddenly necessary and if all important changes have been made...

**Comment by aenonGit** [comment]
it should be fixed now with `2.0.2`, let me know

**Comment by aenonGit** [comment]
just take into account #58 I've put also latest update on this release

**Comment by vipinkviswanath** [comment]
@aenonGit  
How to take this project as a service in another application?Or is it possible to build app module and use this project itself ?
Also please respond to my query #62

**Comment by aenonGit** [comment]
you can do it either way. You can use it as a library as @mocle does (am I correct?). Or as I do, I've included it as a separate module and included this way

-- settings.gradle
`include ':sipservice'`
`project(':sipservice').projectDir = file('libs/pjsip-android/sipservice')`

-- app level build.gradle
`implementation project(':sipservice')`

**Comment by vipinkviswanath** [comment]
@aenonGit 
Can you explain the procedure of importing as a module.please?

**Comment by aenonGit** [comment]
just clone the repo in the root directory of your app, and use the lines I provided you above, then change the path accordingly
