### ISSUE TITLE
call error

### ISSUE THREAD

**Issue by cjcj125125** [VoiSmart/pjsip-android#61]
i use    SipServiceCommand.makeDirectCall（）  ,but get the following information:
onCallState - accountID: sip:10000@101.200.80.70, callID: 1, callStateCode: PJSIP_INV_STATE_DISCONNECTED, callStatusCode: PJSIP_SC_REQUEST_TERMINATED, connectTimestamp: 0, isLocalHold: false, isLocalMute: false, isLocalVideoMute: false

could you help me??  In addition i use  SipServiceCommand.makeCall  returns an error

**Comment by aenonGit** [comment]
`makeDirectCall` is used for direct calls over pbx not requiring authentication. Does `101.200.80.70` is such the case? If not you need to register and then make regular call through `makeCall`.

Show me some code, maybe I can help more

**Comment by cjcj125125** [comment]
Thank you for your answer. I have found the problem, but now I have found a new one. The connection cannot be done on 4G network, but it can be done on wifi.

**Comment by aenonGit** [comment]
Maybe something related to nat traversal? Without logs or code or errors I can't do much more here :)

**Comment by aenonGit** [comment]
close due to inactivity
