### ISSUE TITLE
UnSuccessful registration with twilio account.(PJSIP_SC_PROXY_AUTHENTICATION_REQUIRED).Other accounts Working.

### ISSUE THREAD

**Issue by vipinkviswanath** [VoiSmart/pjsip-android#62]
When using twilio sip account the broadcast receiver logs the following.

2019-03-11 14:29:28.810 21092-21092/package D/SipServiceBR: onRegistration - accountID: sip:***@***.***.***.twilio.com, registrationStateCode: PJSIP_SC_TRYING
2019-03-11 14:29:28.810 21092-21092/package D/REG: RegisteredaccountIDregistrationCode
2019-03-11 14:29:29.197 21092-21092/package D/SipServiceBR: onRegistration - accountID: sip:***@***.***.***.twilio.com, registrationStateCode: PJSIP_SC_PROXY_AUTHENTICATION_REQUIRED

**Comment by aenonGit** [comment]
maybe twilio uses/requires `tls` which is not shipped by default with this library? Maybe just maybe, I have never tested with twilio. Our use case is Freeswitch and works fine.

**IF** that's the case you could try to configure the endpoint (SipService.java -> startStack) to support the TLS protocol.

wish I could help more :(

**Comment by vipinkviswanath** [comment]
@aenonGit By the way what should be set in contactUriParams ?

**Comment by aenonGit** [comment]
I use it to send additional information along the `Contact Header` (e.g. the FCM token). You can just set it as an empty string (till I set it that way by default)

**Comment by vipinkviswanath** [comment]
@aenonGit  Glad that you are supporting well
Can you please show me an example of using Broadcastreceiver's value to update ui ,starting new activity etc.
I mean registering the receiver and performing some action based on its results.

**Comment by vipinkviswanath** [comment]
@aenonGit 
Is the OpenSSL enabled in this library?
