### ISSUE TITLE
How to answer the phone？

### ISSUE THREAD

**Issue by cjcj125125** [VoiSmart/pjsip-android#63]
In the BroadcastEventReceiver class, I can listen for incoming calls, but at this point the activity has finished. How do I open an activity so that the user can answer the call and do something else?

**Comment by aenonGit** [comment]
What do u mean by `at this point the activity has finished`. Btw I extend that class in my app module and eventually I start/restart whatever needs to be started (e.g. a service/activity or else)

**Comment by cjcj125125** [comment]
很感谢收到你的回复，我现在已经完成了简单的拨打和接听，另外我想知道视频电话的时候如何查看预览窗口，我按照你的方法实现了，但是只能看到对方的视频窗口，不能看到自己的预览窗口，你能给我一些帮助吗？以下是我的代码，请指点，非常感谢

<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <SurfaceView
        android:id="@+id/surface_income"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <SurfaceView
        android:id="@+id/surface_myself"
        android:layout_width="120dp"
        android:layout_height="180dp"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_marginTop="25dp"
        android:layout_marginEnd="15dp"  />
</android.support.constraint.ConstraintLayout>

//This is the method I use
  SipServiceCommand.setupIncomingVideoFeed(this, accountID, callID, surfaceViewCome.getHolder().getSurface());
        SipServiceCommand.startVideoPreview(this, accountID, callID, surfaceViewMyself.getHolder().getSurface());

**Comment by vipinkviswanath** [comment]
@aenonGit 
It will be good if you provide the android app project itself which contains this service.So that we can understand the whole communication.(mainly using the receiver to update or create new UI,accept incoming calls etc)

**Comment by cjcj125125** [comment]
My train of thought is open when receiving radio activity (this is a workable UI, answer, hang up, etc.), the first registered eventbus in this activity, and then the radio to send all kinds of state, the activity can operate, but the fact is that I have now completed the function, but don't know how to mute and h-f state switch, can you tell me which method to use? thank you

**Comment by cjcj125125** [comment]
Can you make calls on 4G while you're using it? I can only make and receive calls in wifi

**Comment by cjcj125125** [comment]
> 什么ü意思`at this point the activity has finished`。顺便说一句，我在我的应用程序模块中扩展了该类，最终我启动/重新启动需要启动的任何内容（例如服务/活动或其他）
How do I switch between hands-free and mute? Which method is used? I have a problem with the following method：
  SipServiceCommand.setCallHold(this,accountID,callID,voiceHold);
 SipServiceCommand.toggleCallMute(this,accountID,callID);

**Comment by aenonGit** [comment]
y'all right, but at the moment I'm unable to provide that, If u could just wait a little longer I'll provide a minimal demo

**Comment by aenonGit** [comment]
samples from the official repo can be found here, it is trivial to apply to this

https://github.com/pjsip/pjproject/tree/master/pjsip-apps/src/swig/java
