### ISSUE TITLE
The current version is not able to run on x86 architecture due to text relocation. can You recompile the libraries for me .(Found solution in the pjsip builder project.But dont know how to build properly.)

### ISSUE THREAD

**Issue by vipinkviswanath** [VoiSmart/pjsip-android#70]

**Comment by aenonGit** [comment]
building the pjsip-builder is pretty straighforward, you can try an ubuntu container to ease the process. But the x86 arch problem is a known one. You can try to recompile it with different openssl/ndk/else version. But I can't guarantee it would work.

**Comment by vipinkviswanath** [comment]
@aenonGit Thanks
