### ISSUE TITLE
Incoming call not detected when app is not in foreground/closed.How to register for incoming call always even when app is closed?

### ISSUE THREAD

**Issue by vipinkviswanath** [VoiSmart/pjsip-android#71]

**Comment by vipinkviswanath** [comment]
How to register for incoming call always even when app is closed?

**Comment by dsvignesh** [comment]
Use broadcast receiver for detecting incoming call.

**Comment by vipinkviswanath** [comment]
@dsvignesh  But the service is stopping with app life cycle.I tried to call service again when ondestroy and is working but the problem is , again after some time service is stopping.Do we need a foreground service with notification here?.

**Comment by aenonGit** [comment]
either you start it as a foreground service (with notification etc... ) or you use push notification (there is a parameter you can configure `setContactUriParams` which adds info (such as the fcm token) to the registration contact header and can be used by the pbx to contact the enduser via push notificaiton

**Comment by vipinkviswanath** [comment]
@aenonGit Thanks

**Comment by Huu-Thai** [comment]
> you use push notification (there is a parameter you can configure `setContactUriParams` which adds info (such as the fcm token) to the registration contact header and can be used by the pbx to contact the enduser via push notificaiton

can you add more detail , my server can detect incoming call but it after 0.5s , It can delay incoming call to wait notification (uncertain). Do you have any other way?

**Comment by aenonGit** [comment]
I don't think there is any other way, other than having your app always in background
