### ISSUE TITLE
Error generating Device Unique ID

### ISSUE THREAD

**Issue by cmendes0101** [VoiSmart/pjsip-android#72]
I'm having crashing issues related to registration and it presents in a few ways, sometimes with logs sometimes without.
`
D/SipServiceBR: SIP service stack started
D/SipService: [SipLogWriter] 11:11:23.513            pjsua_acc.c  Adding account: id=sip:username@asterisk
D/SipService: [SipLogWriter] 11:11:23.514            pjsua_acc.c  .Account sip:username@asterisk added with id 0
D/SipService: [SipLogWriter] 11:11:23.514            pjsua_acc.c  .Acc 0: setting registration..
D/SipService: [SipLogWriter] 11:11:23.521         guid_android.c  ..Error generating Device Unique ID
W/libc: malloc(180428196007448000) failed: returning null pointer
D/SipService: [SipLogWriter] 11:11:23.523            pjsua_acc.c  ..Unable to create/send REGISTER: Not enough memory (PJ_ENOMEM) [status=70007]
D/SipService: SIP account sip:auth0-5cb42c96fc295a0ec48ed1bb@asterisk successfully added
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x726f5f6176615a in tid 4480 (SipService), pid 4396
`

I see this is the Fixed Call-ID patch but I'm not sure why it would have an error or how to debug where it fails when generating on the patch.

I have had a different crash on registration where it throws that it can't find the class PjCallID. Then I reopen and it will register successfully so not sure why PjCallId would not be found per the code.

Other times when it crashes I just get this only:
`
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x726f5f6176615a in tid 4480 (SipService), pid 4396
`
Tested on Android 9 and 10. Not sure how to debug farther, just breakpoints till it executes the pjsip SWIG code

**Comment by aenonGit** [comment]
you are absolutely right, on 9 and especially 10 the `Build.getSerial()` won't work anymore. To mitigate you can try it on 8 and lower. But I'm about to remove that, I will allow to set the `Call-ID` directly while creating the sip account. In such scenario one can set any valid value :)

Stay Tuned

**Comment by cmendes0101** [comment]
I just checked out the changes for getSerial(), that makes sense. I guess it'll require permission and that's usually only from system apps.
That change sounds good! looking forward to trying it out and thanks for jumping on it so quick

**Comment by cmendes0101** [comment]
I tested out that commit and seems to be working for that issue. Thank you!

I do still have some random crashes on outbound call and registration but I don't think it's related to the callId issue. Digging through some more

**Comment by aenonGit** [comment]
Thanks! Let me know
