### ISSUE TITLE
What is Realm in SipAccountData?

### ISSUE THREAD

**Issue by vipinkviswanath** [VoiSmart/pjsip-android#73]

**Comment by aenonGit** [comment]
is the part of the sip uri after the `@`.

e.g.: in `sip:john@anyvalidsiprealm.com` the `anyvalidsiprealm.com` is the realm part, which can be different from the host parameter.

**Comment by vipinkviswanath** [comment]
so what is host in the above example? How host part varies then?
In user@sip.example.com:5060 .what is the host part ?

**Comment by vipinkviswanath** [comment]
Consider username@example.onsip.com 
what is host, Realm here?

**Comment by aenonGit** [comment]
realm is `example.onsip.com`, host i don't know. Where is the pbx hosted? ;-)

**Comment by vipinkviswanath** [comment]
was really a silly question , Sorry :)
