### ISSUE TITLE
Just a question. Do you plan to switch to pjsip 2.9 in the near future?

### ISSUE THREAD

**Issue by SergeyMilevskiy** [VoiSmart/pjsip-android#77]

**Comment by aenonGit** [comment]
I hope I will. What I mean is: I've tried both 2.7 and 2.8 releases, but I've had some issue with NAT and Wi-Fi when answering calls. As soon as I have some spare time I'll try with the 2.9.

Anyway feel free to try it out yourself with the build project `pjsip-android-builder` which I use to build this one.

**Comment by SergeyMilevskiy** [comment]
Thank you for the answer, I also have some issues with NAT and Wi-Fi not sure where the problem is lying, but I'm getting PJSIP SC_REQUEST TIMEOUT. I thought the problem with IPv6 but pjsip for the iOS works well on the same router.

**Comment by SergeyMilevskiy** [comment]
Hi there, just want to say, I've resolved issue with NAT and Wifi. You need to switch on TLS instead TCP for media, if you need some hints let me know.
