### ISSUE TITLE
How to set endpt.disable_tcp_switch configuration ?

### ISSUE THREAD

**Issue by KiPSOFT** [VoiSmart/pjsip-android#81]
Hi,

I getting UDP size exceed error and need disable tcp switch setting. How to set endpt.disable_tcp_switch configuration ?

https://trac.pjsip.org/repos/wiki/Using_SIP_TCP#switch

**Comment by zackbugti** [comment]
[Help me urgently, its so urgent please please please]
@KiPSOFT  Sir please help me out too. I have downloaded this whole package and built, but it isn't running and I am facing difficulty understanding the code. So please help me out how to make an application based on this. I need to develop just a simple application that could send/receive messages and calls. Please help me.

**Comment by aenonGit** [comment]
> Hi,
> 
> I getting UDP size exceed error and need disable tcp switch setting. How to set endpt.disable_tcp_switch configuration ?
> 
> https://trac.pjsip.org/repos/wiki/Using_SIP_TCP#switch

Why can't you enable te tcp transport? Btw that method is not exposed to the java binding, but you are free to do that by directly modifing the pjsua2 wrapper in the builder project

**Comment by KiPSOFT** [comment]
Hi, our provider not support tcp. We are compile pjsip library include PJSIP_DONT_SWITCH_TO_TCP compile define.

**Comment by rohitvc** [comment]
@KiPSOFT we too ourself add the `PJSIP_DONT_SWITCH_TO_TCP` in [build_pjsip.sh](https://github.com/rohitvc/react-native-pjsip-builder/blob/master/android/build_pjsip.sh#L18-L19) file 

Build a new `release.tar.gz` but still we are seeing the following error.

```
endpoint  ....Request msg INVITE/cseq=27756 (tdta0x70b237f0a8) exceeds UDP size threshold (1300), sending with TCP
Temporary failure in sending Request msg INVITE/cseq=27756 (tdta0x70b237f0a8), will try next server: Unsuitable transport selected (PJSIP_ETPNOTSUITABLE)
```

Anything here?
