### ISSUE TITLE
How to play beep sound during call? and record with recording call, even receiver can listen the beep

### ISSUE THREAD

**Issue by iosparesh** [VoiSmart/pjsip-android#82]
I have working pjsip Which can make call and receive. I have implemented the recording call feature in my project. Now i want to play a beep sound and that beep sound should be heard by receiver and it should be in recording.

**Comment by zackbugti** [comment]
[Help me urgently, its so urgent please please please]
@iosparesh  Sir please help me out too. I have downloaded this whole package and built, but it isn't running and I am facing difficulty understanding the code. So please help me out how to make an application based on this. I need to develop just a simple application that could send/receive messages and calls. Please help me.

**Comment by iosparesh** [comment]
You should use SO file for pjsip library as suggested in official documentation https://trac.pjsip.org/repos/wiki/Getting-Started/Android

Then you need to understand how SIP register and unregister the user, Do you have asterisk server setup?. If not, you can install it.
https://www.asterisk.org/

Registration takes some information in which a very important is you account information extension number, password, server.
Extra information is what transport you gonna use. TCP, UDP, TLS.
MAX calls.
you need to register callback function which is very important. which help you get notified and debug the flow.

If your asterisk infrastructure includes proxy server then you need to provide information for that too.

this is simple registration 

protected void setDefaultSendersInfo() {
accCfg.setIdUri(SipSharedPref.getInstance(SipBaseActivity.this).readString(getString(R.string.sip_account_id)));
        accCfg.getRegConfig().setRegistrarUri(SipSharedPref.getInstance(SipBaseActivity.this).readString(getString(R.string.sip_registrar)));
        AuthCredInfoVector creds = accCfg.getSipConfig().
                getAuthCreds();
        creds.clear();
        if (SipSharedPref.getInstance(SipBaseActivity.this).readString(getString(R.string.sip_user_name)).length() != 0) {
            creds.add(new AuthCredInfo("Digest", "*",
                    SipSharedPref.getInstance(SipBaseActivity.this).readString(getString(R.string.sip_user_name)), 0,
                    SipSharedPref.getInstance(SipBaseActivity.this).readString(getString(R.string.sip_password))));
        }

        StringVector proxies = accCfg.getSipConfig().getProxies();
        proxies.clear();
        proxies.add("");

        / Enable ICE /
        accCfg.getNatConfig().setIceEnabled(false);

        / Finally /
        try {
            account.modify(accCfg);
        } catch (Exception e) {
            System.out.println(e);
            Log.e(tag, "Exception ::" + e.getMessage());
        }
    }


Before you register with new you should check if any account already exist then unregister it.

**Comment by zackbugti** [comment]
Sir as you have told, I have deployed SIP server that is Kamailio not Asterik. and I have tested these servers by existing VOIP apps. Now I only need to develop the app. Sir it is to state here that I am a student of final year and I took this whole idea as my final year project, but it was so tough that I couldn't met the requirements in time. Most of my time was spent in Server deployment over Ubuntu. Now I am heavily stranded as I have about 10 to 15 days to submit this project to my supervisor and go for my Viva. Time is so short and I have to do something. Sir please help me, if you can. See its the matter of my career. If I fail to submit in time, University admin can put me on extra semester. 
I only need to make an app able to send/receive messages and audio calls only. Please help me. 
I'll be highly indebted to you. 
my email: ahmadfarazbugti@gmail.com

**Comment by aenonGit** [comment]
> I have working pjsip Which can make call and receive. I have implemented the recording call feature in my project. Now i want to play a beep sound and that beep sound should be heard by receiver and it should be in recording.

Would a dtmf be good for you?
