### ISSUE TITLE
How to set ’ConnectDuration‘

### ISSUE THREAD

**Issue by zhanglihow** [VoiSmart/pjsip-android#89]
Hello, my sip connect time has always been 118s, and I want to change it,
I see SipCall.getInfo().getConnectDuration().setSec(), but it doesn't work,
Can you tell me how to set it up?

**Comment by aenonGit** [comment]
what do u expect by calling that method? That's something related to the call duration -> https://www.pjsip.org/pjsip/docs/html/structpj_1_1CallInfo.htm#ad3faef4f3e92fbd2d07d8b30705a35b9

**Comment by zhanglihow** [comment]
> what do u expect by calling that method? That's something related to the call duration -> https://www.pjsip.org/pjsip/docs/html/structpj_1_1CallInfo.htm#ad3faef4f3e92fbd2d07d8b30705a35b9

我想设置通话时间长一点，现在连通118秒就断开了。我看到log的duration=118s

**Comment by zhanglihow** [comment]
> what do u expect by calling that method? That's something related to the call duration -> https://www.pjsip.org/pjsip/docs/html/structpj_1_1CallInfo.htm#ad3faef4f3e92fbd2d07d8b30705a35b9

I want to set the talk time a little longer, now it is disconnected after 118 seconds of connection. I see the duration of the log = 118s

**Comment by zhanglihow** [comment]
It should be automatically disconnected after 118s after sip connection, every time

**Comment by aenonGit** [comment]
I don't think you can do that there. Why is your call dropped after 118s?

**Comment by zhanglihow** [comment]
I don't know, I tried it is not the problem of the server. Do I need to set up a heartbeat mechanism?

**Comment by FongMi** [comment]
But I think it's server problem, cause I can talk very long time.

**Comment by zhanglihow** [comment]
> But I think it's server problem, cause I can talk very long time.
> 
> ![未命名](https://user-images.githubusercontent.com/3471963/71391656-0d3bb280-2640-11ea-9555-9a2aba552696.png)

It may be a problem with my code. What I have used here are:

all:
SipServiceCommand.start ();
SipAccountData data= new SipAccountData ();
data.setRealm ();
data.setHost ();
data.setUsername ();
data.setPassword ();
data.setContactUriParams ();
data.setPort ();
SipServiceCommand.setAccount (application, data);
out:
SipServiceCommand.makeCall ();
in:
SipServiceCommand.acceptIncomingCall ();
or SipServiceCommand.declineIncomingCall ();

Is there anything missing, thanks for replying

**Comment by zhanglihow** [comment]
And I use the computer's sip client to connect to the App, the same sip service, it can be a long time, so ...

**Comment by aenonGit** [comment]
we need more info here:
1) Logs
2) Sip trace
3) Any other relevant info

**Comment by zhanglihow** [comment]
I uploaded a demo on github, so it is easier to see the problem, please help me to see it. Address: https://github.com/zhanglihow/SipNewTest

**Comment by zhanglihow** [comment]
> we need more info here:
> 
> 1. Logs
> 2. Sip trace
> 3. Any other relevant info

Hello, these are two log files
[https://github.com/zhanglihow/SipNewTest/blob/master/log/call_in.txt](url)
[https://github.com/zhanglihow/SipNewTest/blob/master/log/call_out.txt](url)

**Comment by zhanglihow** [comment]
I found the solution to the problem, my sip server needs to send a heartbeat. SipCall.sendRequest () helped me.
