### ISSUE TITLE
Does Library Support RFC3891 ? 

### ISSUE THREAD

**Issue by mittpatel** [VoiSmart/pjsip-android#90]
Hi There,

We're trying to implement Call Retrieve with Replace Header, would like to know if this library support it ? 

https://www.pjsip.org/pjsip/docs/html/group__PJSIP__REPLACES.htm#ga4c6ba4c0e0cd50fb1c4c77e4974f80f1

**Comment by aenonGit** [comment]
if pjsip 2.6 supports it then this library supports it ...given it has been exposed via pjsua2 interface otherwise it didn't get translated in java
