### ISSUE TITLE
missing jitpack repository

### ISSUE THREAD

**Issue by linglingdasan** [VoiSmart/pjsip-android#91]
ERROR: Failed to resolve: com.github.voismart:crypto:0.1.0
Show in Project Structure dialog
Affected Modules: sipservice

**Comment by dadianzi** [comment]
How to solve it ???

**Comment by aenonGit** [comment]
Encountered the same on travis ci. Will look into it

**Comment by kwangjaeyoo** [comment]
ADDED 

repositories {
    maven { url "https://jitpack.io" }
}

**Comment by aenonGit** [comment]
the problem lies in the root `build.gradle` which lacks of `jitpack`dep. Will fix it soon

**Comment by shadowwalkersteam** [comment]
I'm also facing this issue.

**Comment by aenonGit** [comment]
fixed in 99b3b2f
