### ISSUE TITLE
Position change when Notify recyclerview 

### ISSUE THREAD

**Issue by Kashishagrawal** [VoiSmart/pjsip-android#93]
I am using recyclerview for chating and when i change the status of the image from download to downloading using the notifydatasetchange() or notifyItemChanged(position) then after that my ui little bit scroll down, kindly suggest how can i fix this problem.

**Comment by aenonGit** [comment]
I don't think that's a problem related to the library. I think your problem lies withind the recycler view logic. I would suggest you to check the `DiffUtil`to update your recyclerview.

Closing it
