### ISSUE TITLE
Sip library is not compatible with Android10.

### ISSUE THREAD

**Issue by 839265518** [VoiSmart/pjsip-android#94]

**Comment by aenonGit** [comment]
I'm using it on my Pixel with Android 10 without issue. Could you be more specific?

**Comment by 839265518** [comment]
I have tested it. Different manufacturers have different feedback. I need to test it in detail.

**Comment by aenonGit** [comment]
what's the issue you are encountering?

**Comment by tushar-patil-android** [comment]
@aenonGit I think, If PJSIP version < 2.8 not working on Android 10, as I'm facing same issue.

**Comment by aenonGit** [comment]
I have been using this library (shipping pjsip 2.6) on my Pixel with both Android 10 and Android 11 and I've never encountered problems. What are the problems you are encountering?

**Comment by aenonGit** [comment]
closing since it's related to an outdated pjsip version
